url: http://apmtips.com
title: APM tips blog
subtitle: Blog about application monitoring.
author: Sergey Kanzhelev
simple_search: https://www.google.com/search
description:

# Twitter
twitter_user: SergeyKanzhelev
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: apmtips
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-56791310-1

