apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: apmtips-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apmtips
spec:
  hosts:
  - "*"
  gateways:
  - apmtips-gateway
  http:
  - name: overrides
    match:
    - uri:
        prefix: /images
    route:
    - destination:
        host: apmtips
        port:
          number: 80
  - name: default
    route:
    - destination:
        host: apmtips
        port:
          number: 80